create extension if not exists "pgcrypto";

create type public.profile_role as enum ('admin', 'member');
create type public.client_status as enum ('lead', 'active', 'inactive');
create type public.task_priority as enum ('low', 'medium', 'high');
create type public.task_status as enum ('pending', 'done', 'cancelled');
create type public.proposal_status as enum ('draft', 'sent', 'approved', 'rejected');
create type public.entry_type as enum ('income', 'expense');

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role public.profile_role not null default 'member',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.clients (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  company text,
  email text,
  phone text,
  status public.client_status not null default 'lead',
  tags text[] not null default '{}',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid not null references public.clients(id) on delete cascade,
  name text not null,
  position text,
  email text,
  phone text,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid references public.clients(id) on delete set null,
  title text not null,
  description text,
  priority public.task_priority not null default 'medium',
  status public.task_status not null default 'pending',
  due_date date,
  assigned_to uuid references auth.users(id) on delete set null,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.proposals (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid not null references public.clients(id) on delete cascade,
  title text not null,
  amount numeric(12, 2) not null check (amount > 0),
  status public.proposal_status not null default 'draft',
  valid_until date,
  details text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.financial_entries (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  client_id uuid references public.clients(id) on delete set null,
  entry_type public.entry_type not null,
  category text,
  description text,
  amount numeric(12, 2) not null check (amount > 0),
  occurred_on date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.audits (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  entity text not null,
  entity_id uuid,
  action text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists clients_owner_idx on public.clients(owner_id);
create index if not exists contacts_owner_idx on public.contacts(owner_id);
create index if not exists tasks_owner_idx on public.tasks(owner_id);
create index if not exists proposals_owner_idx on public.proposals(owner_id);
create index if not exists financial_owner_idx on public.financial_entries(owner_id);
create index if not exists audits_owner_idx on public.audits(owner_id);

create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at before update on public.profiles
for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_clients_updated_at on public.clients;
create trigger trg_clients_updated_at before update on public.clients
for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_contacts_updated_at on public.contacts;
create trigger trg_contacts_updated_at before update on public.contacts
for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_tasks_updated_at on public.tasks;
create trigger trg_tasks_updated_at before update on public.tasks
for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_proposals_updated_at on public.proposals;
create trigger trg_proposals_updated_at before update on public.proposals
for each row execute procedure public.handle_updated_at();

drop trigger if exists trg_financial_updated_at on public.financial_entries;
create trigger trg_financial_updated_at before update on public.financial_entries
for each row execute procedure public.handle_updated_at();

alter table public.profiles enable row level security;
alter table public.clients enable row level security;
alter table public.contacts enable row level security;
alter table public.tasks enable row level security;
alter table public.proposals enable row level security;
alter table public.financial_entries enable row level security;
alter table public.audits enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
for select using (auth.uid() = user_id);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
for insert with check (auth.uid() = user_id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
for update using (auth.uid() = user_id);

drop policy if exists "clients_owner_policy" on public.clients;
create policy "clients_owner_policy" on public.clients
for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "contacts_owner_policy" on public.contacts;
create policy "contacts_owner_policy" on public.contacts
for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "tasks_owner_policy" on public.tasks;
create policy "tasks_owner_policy" on public.tasks
for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "proposals_owner_policy" on public.proposals;
create policy "proposals_owner_policy" on public.proposals
for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "financial_owner_policy" on public.financial_entries;
create policy "financial_owner_policy" on public.financial_entries
for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "audits_owner_policy" on public.audits;
create policy "audits_owner_policy" on public.audits
for all using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

create or replace view public.dashboard_metrics
with (security_invoker = true)
as
select
  auth.uid() as owner_id,
  (select count(*) from public.clients c where c.owner_id = auth.uid() and c.status = 'active')::int as active_clients,
  (select count(*) from public.clients c where c.owner_id = auth.uid() and c.status = 'lead')::int as leads,
  (select count(*) from public.tasks t where t.owner_id = auth.uid() and t.status = 'pending')::int as pending_tasks,
  coalesce((
    select sum(case when f.entry_type = 'income' then f.amount else 0 end)
    from public.financial_entries f
    where f.owner_id = auth.uid()
      and date_trunc('month', f.occurred_on) = date_trunc('month', now())
  ), 0)::numeric(12,2) as monthly_income,
  coalesce((
    select sum(case when f.entry_type = 'expense' then f.amount else 0 end)
    from public.financial_entries f
    where f.owner_id = auth.uid()
      and date_trunc('month', f.occurred_on) = date_trunc('month', now())
  ), 0)::numeric(12,2) as monthly_expense;

grant select on public.dashboard_metrics to authenticated;
